import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'

library.add(fas)

export { default as Button } from './components/Button'
export { default as Menu } from './components/Menus'
export { default as AutoComplete } from './components/AutoComplete'
export { default as Alert } from './components/Alerts'
export { default as Icon } from './components/Icon'
export { default as Input } from './components/Input'
export { default as Transition } from './components/Transitions'
export { default as Tree } from './components/Tree'
export { default as Checkbox } from './components/Checkbox'
export { default as DatePicker } from './components/InputDatePicker'
export { default as Progress } from './components/Progress'
export { default as Select } from './components/Select'
export { default as Tab } from './components/Tabs'
export { default as Modal } from './components/Modal'
export { default as Message } from './components/Message'