name: Node CI

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  #   types: [closed]

env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get commit message
        run: |
          echo commitmsg=$(git log --format=%B -n 1 ${{ github.event.after }})  >> $GITHUB_ENV
      - name: Show commit message
        run: echo $commitmsg

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn

      - name: Build, and test
        run: |
          yarn lint
          yarn build
          yarn bundlesize
          yarn test
        env:
          CI: true

      - name: Release
        if: startsWith( env.commitmsg , 'chore(release):' )
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
